<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="parter.aspx.cs" Inherits="moni1.parter" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style3 {
            text-align: center;
        }
        .auto-style4 {
            font-size: xx-large;
            background-color: #F7F7DE;
        }
        .auto-style5 {
            font-size: large;
            background-color: #F7F7DE;
        }
        .auto-style6 {
            width: 392px;
        }
        .auto-style7 {
            margin-left: 0px;
        }
        .auto-style8 {
            width: 392px;
            height: 61px;
        }
        .auto-style9 {
            height: 61px;
        }
        .auto-style10 {
            background-color: #F7F7DE;
        }
    </style>
</head>
<body style="background-image: url('80408-107252-image_banner.jpg'); background-repeat: no-repeat; background-attachment: fixed; background-position: center center; background-size: cover">
    <form id="form1" runat="server">
        <div class="auto-style3">
            <strong>
            <asp:Label ID="Label1" runat="server" CssClass="auto-style4" Text="揪伴參與活動網"></asp:Label>
            </strong>
        </div>
        <table class="auto-style1">
            <tr>
                <td class="auto-style8">
                    <asp:Label ID="userLB" runat="server" CssClass="auto-style5" Text="將顯示使用者資訊"></asp:Label>
                </td>
                <td class="auto-style9">
                    <div class="auto-style3">
                    </div>
                    <asp:SqlDataSource ID="userJoinDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT event.event_name, event.event_convener_phone, event.event_time, event.event_memo, [join].join_id FROM [join] INNER JOIN event ON [join].join_eventId = event.event_id WHERE ([join].join_phone = @join_phone)" DeleteCommand="DELETE FROM [join] WHERE (join_id = @join_id)">
                        <DeleteParameters>
                            <asp:ControlParameter ControlID="GridView1" Name="join_id" PropertyName="SelectedDataKey" />
                        </DeleteParameters>
                        <SelectParameters>
                            <asp:SessionParameter Name="join_phone" SessionField="phone" />
                        </SelectParameters>
                    </asp:SqlDataSource>
                </td>
            </tr>
            <tr>
                <td class="auto-style6">
                            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                            <EditRowStyle BackColor="#999999" />
                            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                            <SortedAscendingCellStyle BackColor="#E9E7E2" />
                            <SortedAscendingHeaderStyle BackColor="#506C8C" />
                            <SortedDescendingCellStyle BackColor="#FFFDF8" />
                            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                        </asp:GridView>
                    </td>
                <td>
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" CssClass="auto-style7" DataKeyNames="join_id" DataSourceID="userJoinDataSource" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical">
                        <AlternatingRowStyle BackColor="White" />
                        <Columns>
                            <asp:BoundField DataField="event_name" HeaderText="活動名稱" SortExpression="event_name" />
                            <asp:BoundField DataField="event_convener_phone" HeaderText="活動發起者電話" SortExpression="event_convener_phone" />
                            <asp:BoundField DataField="event_time" HeaderText="活動時間" SortExpression="event_time" />
                            <asp:BoundField DataField="event_memo" HeaderText="活動備註" SortExpression="event_memo" />
                            <asp:BoundField DataField="join_id" HeaderText="參加編號" InsertVisible="False" ReadOnly="True" SortExpression="join_id" />
                        </Columns>
                        <FooterStyle BackColor="#CCCC99" />
                        <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                        <RowStyle BackColor="#F7F7DE" />
                        <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#FBFBF2" />
                        <SortedAscendingHeaderStyle BackColor="#848384" />
                        <SortedDescendingCellStyle BackColor="#EAEAD3" />
                        <SortedDescendingHeaderStyle BackColor="#575357" />
                    </asp:GridView>
                </td>
            </tr>
            <tr>
                <td class="auto-style6">&nbsp;</td>
                <td>
                    <asp:Label ID="eventSearchLB" runat="server" CssClass="auto-style10" Text="輸入活動名稱："></asp:Label>
                    <asp:TextBox ID="eventSearchTB" runat="server"></asp:TextBox>
                    <asp:Button ID="eventSearchBT" runat="server" OnClick="eventSearchBT_Click" Text="查詢" />
                    <asp:SqlDataSource ID="eventSearchDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT event.event_id, event.event_name, event.event_time, [Table].member_name, COUNT([Table].member_name) AS Expr1 FROM event INNER JOIN [Table] ON event.event_convener_phone = [Table].member_phone INNER JOIN [join] ON event.event_id = [join].join_eventId GROUP BY event.event_id, event.event_name, event.event_time, [Table].member_name HAVING (event.event_name = @event_name)">
                        <SelectParameters>
                            <asp:SessionParameter Name="event_name" SessionField="eventSearch" />
                        </SelectParameters>
                    </asp:SqlDataSource>
                </td>
            </tr>
            <tr>
                <td class="auto-style6">&nbsp;</td>
                <td>
                    <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="event_id" DataSourceID="eventSearchDataSource" ForeColor="Black" GridLines="Vertical">
                        <AlternatingRowStyle BackColor="White" />
                        <Columns>
                            <asp:BoundField DataField="event_id" HeaderText="活動編號" InsertVisible="False" ReadOnly="True" SortExpression="event_id" />
                            <asp:BoundField DataField="event_name" HeaderText="活動名稱" SortExpression="event_name" />
                            <asp:BoundField DataField="event_time" HeaderText="活動時間" SortExpression="event_time" />
                            <asp:BoundField DataField="member_name" HeaderText="召集人名字" SortExpression="member_name" />
                            <asp:BoundField DataField="Expr1" HeaderText="已參加人數" ReadOnly="True" SortExpression="Expr1" />
                        </Columns>
                        <FooterStyle BackColor="#CCCC99" />
                        <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                        <RowStyle BackColor="#F7F7DE" />
                        <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#FBFBF2" />
                        <SortedAscendingHeaderStyle BackColor="#848384" />
                        <SortedDescendingCellStyle BackColor="#EAEAD3" />
                        <SortedDescendingHeaderStyle BackColor="#575357" />
                    </asp:GridView>
                </td>
            </tr>
            <tr>
                <td class="auto-style6">&nbsp;</td>
                <td>
                    <asp:Label ID="insertEventLB" runat="server" CssClass="auto-style10" Text="新增參加活動號："></asp:Label>
                    <asp:TextBox ID="insertEventTB" runat="server"></asp:TextBox>
                    <asp:Button ID="insertEventBT" runat="server" OnClick="insertEventBT_Click" Text="加入活動" />
                </td>
            </tr>
        </table>
    </form>
</body>
</html>
