<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="parter.aspx.cs" Inherits="moni1.parter" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style3 {
            text-align: center;
        }
        .auto-style4 {
            font-size: xx-large;
            background-color: #FFFFFF;
        }
        .auto-style5 {
            font-size: large;
            background-color: #FFFFFF;
        }
        .auto-style6 {
            width: 392px;
        }
        .auto-style7 {
            margin-left: 0px;
        }
        .auto-style8 {
            width: 392px;
            height: 61px;
        }
        .auto-style9 {
            height: 61px;
        }
    </style>
</head>
<body style="background-image: url('80408-107252-image_banner.jpg'); background-repeat: no-repeat; background-attachment: fixed; background-position: center center; background-size: cover">
    <form id="form1" runat="server">
        <div class="auto-style3">
            <strong>
            <asp:Label ID="Label1" runat="server" CssClass="auto-style4" Text="揪伴參與活動網"></asp:Label>
            </strong>
        </div>
        <table class="auto-style1">
            <tr>
                <td class="auto-style8">
                    <asp:Label ID="userLB" runat="server" CssClass="auto-style5" Text="將顯示使用者資訊"></asp:Label>
                </td>
                <td class="auto-style9">
                    <div class="auto-style3">
                    </div>
                    <asp:SqlDataSource ID="userJoinDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT event.event_name, event.event_convener_phone, event.event_time, event.event_memo, [join].join_id FROM [join] INNER JOIN event ON [join].join_eventId = event.event_id WHERE ([join].join_phone = @join_phone)" DeleteCommand="DELETE FROM [join] WHERE (join_id = @join_id)">
                        <DeleteParameters>
                            <asp:ControlParameter ControlID="GridView1" Name="join_id" PropertyName="SelectedDataKey" />
                        </DeleteParameters>
                        <SelectParameters>
                            <asp:SessionParameter Name="join_phone" SessionField="phone" />
                        </SelectParameters>
                    </asp:SqlDataSource>
                </td>
            </tr>
            <tr>
                <td class="auto-style6">
                            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                            <EditRowStyle BackColor="#999999" />
                            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                            <SortedAscendingCellStyle BackColor="#E9E7E2" />
                            <SortedAscendingHeaderStyle BackColor="#506C8C" />
                            <SortedDescendingCellStyle BackColor="#FFFDF8" />
                            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                        </asp:GridView>
                    </td>
                <td>
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" CssClass="auto-style7" DataKeyNames="join_id" DataSourceID="userJoinDataSource">
                        <Columns>
                            <asp:BoundField DataField="event_name" HeaderText="活動名稱" SortExpression="event_name" />
                            <asp:BoundField DataField="event_convener_phone" HeaderText="活動發起者電話" SortExpression="event_convener_phone" />
                            <asp:BoundField DataField="event_time" HeaderText="活動時間" SortExpression="event_time" />
                            <asp:BoundField DataField="event_memo" HeaderText="活動備註" SortExpression="event_memo" />
                            <asp:BoundField DataField="join_id" HeaderText="參加活動編號" InsertVisible="False" ReadOnly="True" SortExpression="join_id" />
                        </Columns>
                    </asp:GridView>
                </td>
            </tr>
            <tr>
                <td class="auto-style6">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        </table>
    </form>
</body>
</html>
